[package]
name = "bot"
version = "0.0.1"
authors = ["Elinvynia <59487684+Elinvynia@users.noreply.github.com>"]
edition = "2018"


[dependencies]
serenity = "0.8.0"
dotenv = "0.15.0"
config = "0.10.1"
reqwest = "0.10.1"
env_logger = "0.7.1"
log = "0.4.8"
rusqlite = { version = "0.21.0", features = ["bundled"] }
