[package]
name = "bot"
version = "0.0.1"
authors = ["Elinvynia <59487684+Elinvynia@users.noreply.github.com>"]
edition = "2018"


[dependencies]
serenity = { git = "https://github.com/Lakelezz/serenity/", branch = "await" }
tokio  = { version = "0.2", features = ["macros", "rt-threaded", "blocking"] }
dotenv = "0.15.0"
config = "0.10.1"
env_logger = "0.7.1"
log = "0.4.8"
sqlx = { version = "0.3", default-features = false, features = ["runtime-tokio", "macros", "sqlite", "postgres"], optional = true }
libsqlite3-sys = { version = "*", features = ["bundled"] }

[features]
default = ["sqlite"]
sqlite = ["sqlx"]
postgres = ["sqlx"]
