name: Deploy
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker image
      uses: whoan/docker-build-with-cache-action@v5
      with:
        image_name: ${{ secrets.DOCKER_USERNAME }}/bot
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
