name: Deploy
on:
  push:
    tags:
    - 'v**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v3
      with:
        image: ${{ secrets.DOCKER_USERNAME }}/bot
        tag: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
